name: Deploy WAR with Dynatrace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #Deploy WAR
      - name: Deploy WAR
        uses: azure/webapps-deploy@v3
        with:
          app-name: MyTESTAPPS
          package: ROOT.war

      #Install Dynatrace OneAgent (persistent path)
      - name: Install Dynatrace OneAgent
        run: |
          mkdir -p /home/site/wwwroot/dynatrace
          cd /home/site/wwwroot/dynatrace

          wget -O Dynatrace-OneAgent.sh "${{ secrets.DT_CONNECTION_POINT }}/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=${{ secrets.DT_TENANTTOKEN }}&flavor=default&include=java"

          chmod +x Dynatrace-OneAgent.sh
          ./Dynatrace-OneAgent.sh APP_LOG_CONTENT_ACCESS=1

      #Configure App Settings + JVM Injection
      - name: Configure Dynatrace
        run: |
          az webapp config appsettings set \
            --name MyTESTAPPS \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --settings \
            DT_TENANT=${{ secrets.DT_TENANT }} \
            DT_TENANTTOKEN=${{ secrets.DT_TENANTTOKEN }} \
            DT_CONNECTION_POINT=${{ secrets.DT_CONNECTION_POINT }} \
            DT_ENABLED=true \
            JAVA_OPTS="-agentpath:/home/site/wwwroot/dynatrace/oneagent/agent/lib64/liboneagentloader.so"

      #Restart App
      - name: Restart App
        run: |
          az webapp restart \
            --name MyTESTAPPS \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
